print("PIGGYBANK")
print("************************")
a=int(input("Enter no. of rs.10 coins:"))
b=int(10*a)
c=int(input("Enter no. of rs. 5 coins:"))
d=int(5*c)
e=int(input("Enter no. of rs. 2 coins:"))
f=int(2*e)
g=int(input("Enter no. of rs. 1 coins:"))
h=int(1*g)
Total=int(b)+int(d)+int(f)+int(h)
print("Total Amount:",Total)
print("**************************")
